# Generated by Django 5.2.4 on 2025-07-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
