# Generated by Django 5.2.4 on 2025-07-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_alter_voucher_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('used', 'Used'), ('expired', 'Expired'), ('disabled', 'Disabled')], default='pending', max_length=10),
        ),
    ]
